### ISSUE TITLE
Untarring members that are sub-directories themselves results in an error

### ISSUE THREAD

**Issue by adam2392** [fatiando/pooch#264]
**Description of the problem**
Related to #223 

I think this issue might not have been resolved for members that are "folders". For example, if you have data:

```
hf_sef/
     MEG/
          subject_a/
                <actual_files>
     SSS/
            another_subdir/
...
```

**Full code that generated the error**
This PR branch: https://github.com/mne-tools/mne-python/pull/9742 

and running: `python -c "import mne; mne.datasets.hf_sef.data_path(force_update=True, verbose=True)"`

Specifically, these lines would break it.
```python
    # instantiate processor that unzips file
    # import pooch
    processor = pooch.Untar(extract_dir=op.join(path, folder_name), 
                            members=[f'hf_sef/{subdir}' for subdir in
                                       ('MEG', 'SSS', 'subjects')])
```

**Full error message**

```
Traceback (most recent call last):
  File "/Users/adam2392/miniconda3/envs/mnex64/lib/python3.8/site-packages/pooch/processors.py", line 228, in _extract_file
    output.write(data_file.read())
AttributeError: 'NoneType' object has no attribute 'read'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<decorator-gen-510>", line 22, in data_path
  File "/Users/adam2392/Documents/mne-python/mne/datasets/hf_sef/hf_sef.py", line 84, in data_path
    return fetch_dataset(dataset_params=data_dict, processor=processor,
  File "/Users/adam2392/Documents/mne-python/mne/datasets/fetch.py", line 234, in fetch_dataset
    fetcher.fetch(fname=archive_name, downloader=downloader,
  File "/Users/adam2392/miniconda3/envs/mnex64/lib/python3.8/site-packages/pooch/core.py", line 549, in fetch
    return processor(str(full_path), action, self)
  File "/Users/adam2392/miniconda3/envs/mnex64/lib/python3.8/site-packages/pooch/processors.py", line 86, in __call__
    self._extract_file(fname, self.extract_dir)
  File "/Users/adam2392/miniconda3/envs/mnex64/lib/python3.8/site-packages/pooch/processors.py", line 230, in _extract_file
    data_file.close()
AttributeError: 'NoneType' object has no attribute 'close'
```

**System information**

* Operating system: MacOS
* Python installation (Anaconda, system, ETS): Miniconda
* Version of Python: 3.8
* Version of this package: 1.5.1
* If using conda, paste the output of `conda list` below:

**Comment by adam2392** [comment]
Possible solution: https://stackoverflow.com/questions/8008829/extract-only-a-single-directory-from-tar

**Comment by leouieda** [comment]
@adam2392 thanks for reporting! This is definitely a  bug. I just checked and our test data includes this use case but I think we never actually implemented the tests. I'll have a look and see if I can reproduce this in a test. It should an easy enough fix (famous last words).

**Comment by leouieda** [comment]
Alright, I've managed to reproduce the error in a test case in #266.
